alias ls="ls -hF"
alias json='python -m json.tool' # for pretty printed json
alias tb='cd ~/git/tastybrew && workon tastybrew'
export PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/local/share/python:/usr/bin:/bin:/usr/sbin:/sbin
export PS1='\[\e[0;32m\][\w]\[\e[0m\] $(vcprompt)\$ '
export EDITOR="vim"
export MACOSX_DEPLOYMENT_TARGET=10.7
# Python startup
export PYTHONSTARTUP=~/.pythonrc
export PYTHONPATH=/usr/local/lib/python2.7/site-packages
# virtualenv
export WORKON_HOME=$HOME/.virtualenvs
. /usr/local/bin/virtualenvwrapper.sh
# PIP
export PIP_LOG_FILE=/tmp/pip-log.txt
export PIP_DOWNLOAD_CACHE=/tmp/pip_cache
# Node.js
export NODE_PATH=/usr/local/lib/node
# Various bash completion scripts
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi
. ~/django/extras/django_bash_completion
