# Aliases
alias ls="ls -hF"
alias json='python -m json.tool' # for pretty printed json
alias rmpyc='find . -name \*\.pyc -delete'
alias z='cd ~/git/zamboni && workon zamboni'
alias zup='z && git checkout master && git pull mozilla master && git submodule sync && git submodule update --init --recursive && ./vendor/src/schematic/schematic migrations'
# Exports
export PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/local/share/python:/usr/bin:/bin:/usr/sbin:/sbin
export PS1='\[\e[0;32m\][\w]\[\e[0m\] $(vcprompt)\$ '
export EDITOR="vim"
# Python startup
export PYTHONSTARTUP=~/.pythonrc
export PYTHONPATH=/usr/local/lib/python2.7/site-packages
export PYTHONDONTWRITEBYTECODE=true
# virtualenv
export WORKON_HOME=$HOME/.virtualenvs
. /usr/local/bin/virtualenvwrapper.sh
export VIRTUALENV_USE_DISTRIBUTE=true
# PIP
export PIP_LOG_FILE=/tmp/pip-log.txt
export PIP_DOWNLOAD_CACHE=/tmp/pip_cache
export PIP_RESPECT_VIRTUALENV=true
# Node.js
export NODE_PATH=/usr/local/lib/node
# Various bash completion scripts
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi
. ~/django/extras/django_bash_completion

